### ISSUE TITLE
Page formatting

### ISSUE THREAD

**Issue by Poruchan** [lenkutchma/sidney#1]
Just after Genisis 2.2.4 update lost page formatting - where I had a full page, no side bar - now there's a sidebar and can't remove it.

**Comment by lenkutchma** [comment]
Hello. I believe this was a bug in Genesis 2.2.4. Try updating to the newly released version 2.2.5 and see if that corrects the problem. Further info ...

http://www.studiopress.com/forums/topic/2-2-4-defect-sidebar-trashing-non-sidebar-page-rolled-er-back/

**Comment by lenkutchma** [comment]
Due to a lack of a response or update this issue is closed.
